version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./laravel:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    depends_on: 
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: desafio-appstorm
      MYSQL_USER: root2
      MYSQL_PASSWORD: root_password2
    ports:
      - "3306:3306"  # Mapeia a porta 3306 do contêiner para a porta 3306 do host
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql

  redis:
    image: redis:latest

volumes:
  mysql_data: